### PR TITLE
Fixes place block

### LINKED ISSUE #9: Blockplacing only works if allowAir is true
https://github.com/MineInAbyss/Geary/blob/fd69fdbb30209ce23e0857c23e0c513183049bf8/spigot/components/src/main/kotlin/com/mineinabyss/geary/minecraft/properties/ConfigurableLocation.kt#L76-L77

Since the blockface is always air, if allowAir is false it does not work.
If it is true, then u can place blocks midair

### PR DESCRIPTION
**Pull request by Boy0000**
Closes #9 

Checks the second block aswell.
ezgif-7-db63ba76a375

### CODE REVIEW

File: geary-commons-papermc/src/main/kotlin/com/mineinabyss/geary/minecraft/properties/ConfigurableLocation.kt [hunk 1]
```diff
@@ -19,7 +19,7 @@ import org.bukkit.entity.Player
  * Useful for actions that wish to run at a specific location but want to remain configurable.
  */
 @Serializable
-public sealed class ConfigurableLocation : EntityProperty<Location>()
+sealed class ConfigurableLocation : EntityProperty<Location>()
```
Comment (DevScyu) [inline geary-commons-papermc/src/main/kotlin/com/mineinabyss/geary/minecraft/properties/ConfigurableLocation.kt:22]: Why did you remove the public from these classes?

Comment (Boy0000) [reply geary-commons-papermc/src/main/kotlin/com/mineinabyss/geary/minecraft/properties/ConfigurableLocation.kt:22]: Just said "redundant" in warnings when comitting so poofed shrug
